# Generated by Django 5.1.5 on 2025-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_created_at_entry_criteria_for_mastery_and_more'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorclass',
            name='prompt_list',
            field=models.ManyToManyField(related_name='class_prompt_lists', to='entries.prompt'),
        ),
        migrations.AddField(
            model_name='supervisorclass',
            name='prompt_override',
            field=models.BooleanField(default=False),
        ),
    ]
