# Generated by Django 5.1.5 on 2025-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentteacher',
            name='grade_levels',
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='grade_levels',
            field=models.ManyToManyField(to='user_auth.gradelevel'),
        ),
    ]
