# Generated by Django 5.1.5 on 2025-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_extenduser_org_invitation_org_studentteacher_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacher',
            name='org',
        ),
        migrations.RemoveField(
            model_name='studentteacher',
            name='grade_levels',
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='grade_levels',
            field=models.JSONField(default=list),
        ),
    ]
