# Generated by Django 5.1.5 on 2025-04-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_studentteacher_grade_levels_delete_gradelevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentteacher',
            old_name='grade_levels',
            new_name='grade_level',
        ),
    ]
