# Generated by Django 5.1.5 on 2025-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_gradelevel_remove_studentteacher_grade_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='gradelevel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
