# Generated by Django 5.1.5 on 2025-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_studentteacher_org_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeLevel',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='org',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='org',
            field=models.ManyToManyField(blank=True, null=True, to='user_auth.organization'),
        ),
    ]
