# Generated by Django 5.1.5 on 2025-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_invitation_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(default='Student Teacher', max_length=100),
            preserve_default=False,
        ),
    ]
