# Generated by Django 5.1.5 on 2025-02-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_delete_gradelevel_remove_extenduser_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='org',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='org',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.organization'),
        ),
    ]
