# Generated by Django 4.2.19 on 2025-03-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_extenduser_role_alter_extenduser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
