# Generated by Django 5.1.6 on 2025-02-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_gradelevel_organization_alter_extenduser_org_and_more'),
        ('user_auth', '0005_invitation_role'),
    ]

    operations = [
    ]
