# Generated by Django 5.1.5 on 2025-02-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_extenduser_org_extenduser_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.organization'),
        ),
    ]
