# Generated by Django 5.1.6 on 2025-02-26 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_organization_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_org', to='user_auth.organization'),
        ),
        migrations.AlterField(
            model_name='studentteacher',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_studentteacher', to='user_auth.organization'),
        ),
    ]
