# Generated by Django 4.2.19 on 2025-03-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_submission_delete_hlpsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_title', models.CharField(max_length=200)),
                ('previous_content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='user_auth.submission')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
