# Generated by Django 4.2.19 on 2025-03-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_submissionedit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='SubmissionEdit',
        ),
    ]
