# Generated by Django 5.1.5 on 2025-04-04 20:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlp', models.IntegerField(default=0)),
                ('lookfor_number', models.IntegerField(default=0)),
                ('score', models.CharField(choices=[('1', '1'), ('2', '2'), ('NA', 'Not Applicable')], default='NA', max_length=2)),
                ('date', models.DateField(default=datetime.date.today)),
                ('comments', models.TextField(default='')),
                ('teacher_reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('seen', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
            ],
        ),
    ]
