# Generated by Django 5.1.6 on 2025-02-26 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='hlp_number',
        ),
        migrations.AddField(
            model_name='entry',
            name='hlp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='lookfor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='teacher_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('NA', 'Not Applicable')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('seen', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
            ],
        ),
    ]
