# Generated by Django 5.1.5 on 2025-04-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to='user_auth.organization'),
        ),
        migrations.AddField(
            model_name='promptresponse',
            name='entry_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt_responses',
            field=models.ManyToManyField(blank=True, to='entries.promptresponse'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='prompt_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='entries.promptresponse'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.supervisor'),
        ),
    ]
