# Generated by Django 5.1.5 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_remove_entry_hlp_number_entry_hlp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
