# Generated by Django 4.2.20 on 2025-04-10 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='criteria_for_mastery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='goal_reflection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision', 'Needs Revision')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='weekly_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('never', 'Never'), ('na', 'N/A')], default='na', max_length=10)),
                ('reflection', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_responses', to='entries.entry')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceForMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='entries.entry')),
            ],
            options={
                'verbose_name': 'Evidence for Mastery',
                'verbose_name_plural': 'Evidences for Mastery',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='prompt_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='entries.promptresponse'),
        ),
    ]
