# Generated by Django 5.1.5 on 2025-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('-1', 'No Choice')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('revised', 'Revised Submission'), ('approved', 'Approved'), ('revision', 'Needs Revision')], default='pending', max_length=10),
        ),
    ]
