# Generated by Django 5.1.5 on 2025-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenceformastery',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='criteria_for_mastery',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='goal_reflection',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='weekly_goal',
        ),
        migrations.RemoveField(
            model_name='promptresponse',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='promptresponse',
            name='indicator',
        ),
        migrations.AddField(
            model_name='entry',
            name='responses',
            field=models.ManyToManyField(blank=True, to='entries.promptresponse'),
        ),
        migrations.AlterField(
            model_name='promptresponse',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='EvidenceForMastery',
        ),
    ]
