# Generated by Django 5.1.5 on 2025-03-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('NA', 'Not Applicable')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='teachercomment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='hlp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.hlp'),
        ),
        migrations.AddField(
            model_name='hlp',
            name='prompts',
            field=models.ManyToManyField(blank=True, to='entries.prompts'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.prompts')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt_override', models.BooleanField(default=False)),
                ('prompt_list', models.ManyToManyField(blank=True, to='entries.prompts')),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.supervisorclass'),
        ),
    ]
