# Generated by Django 5.1.5 on 2025-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_evidenceformastery_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='responses',
            new_name='prompt_responses',
        ),
    ]
