# Generated by Django 5.1.5 on 2025-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_sup_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='teacher_reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
