# Generated by Django 5.1.5 on 2025-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_hlp_prompts_entry_user_alter_entry_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlp',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
