# Generated by Django 5.1.5 on 2025-03-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_hlp_name'),
        ('user_auth', '0002_prompt_supervisor_prompt_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hlp',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='supervisorclass',
            name='prompt_list',
        ),
        migrations.AlterField(
            model_name='answer',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.prompt'),
        ),
        migrations.RemoveField(
            model_name='supervisorclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='supervisorclass',
            name='user',
        ),
        migrations.AlterField(
            model_name='teachercomment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.supervisor'),
        ),
        migrations.DeleteModel(
            name='HLP',
        ),
        migrations.DeleteModel(
            name='Prompts',
        ),
        migrations.DeleteModel(
            name='SupervisorClass',
        ),
    ]
