# Generated by Django 4.2.10 on 2026-05-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0007_teachercomment_rubric_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlp', models.TextField()),
                ('lookfor_number', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='hlp_assignments', to=settings.AUTH_USER_MODEL)),
                ('sup_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlp_assignments', to='user_auth.supervisorclass')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlp_assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
